### ISSUE TITLE
테이블 제작 - 배너 테이블(km_banner)

### ISSUE THREAD

**Issue by hochmun** [hochmun/Kmarket_Project_2nd#196]

**Comment by 094haley** [comment]
km_banner

- [ ] bannerNo : 배너 고유번호
- [ ] bannerName : 배너이름
- [ ] bannerSize: 배너사이즈
- [ ] bannerColor: 배너 색생
- [ ] bannerLink: 배너 링크
- [ ] bannerLocation: 배너 위치
- [ ] bannerSdate: 시작일
- [ ] bannerEdate:  종료일
- [ ] bannerStime: 시작시간
- [ ] bannerEtime: 종료시간
- [ ] bannerStatus:  배너 상태(활성/비활성)

**Comment by 094haley** [comment]
2023/02/23 이해빈 배너 테이블 생성 완료

**Comment by hochmun** [comment]
리뷰 완료
